#!/bin/bash

# 현재 공인 IP 가져오기
PUBLIC_IP=$(curl -s https://api.ipify.org)

# 적용할 대상 파일
ENV_FILE=".env"

# .env 파일 없으면 생성
if [ ! -f "$ENV_FILE" ]; then
  echo "# Auto-generated by update-public-ip.sh" > $ENV_FILE
fi

# 기존 PUBLIC_IP 줄 제거
sed -i '' '/^PUBLIC_IP=/d' "$ENV_FILE"

# 새 PUBLIC_IP 추가
echo "PUBLIC_IP=$PUBLIC_IP" >> "$ENV_FILE"

echo "✅ PUBLIC_IP updated to $PUBLIC_IP in $ENV_FILE"

